### PR TITLE
Rename Helm chart

### PR DESCRIPTION
**Pull request by johnwatson484**
Rename Helm chart

https://eaflood.atlassian.net/browse/PSD-32

### CODE REVIEW

**Comment by johnwatson484** [comment]
It works fine for me?  I had a bit of an issue getting the install script to run, not sure what I did to fix it other than clearing out any existing ffc-demo namespaces.  But once it run it worked fine.

image

**Comment by djbingham** [comment]
> It works fine for me? I had a bit of an issue getting the install script to run, not sure what I did to fix it other than clearing out any existing ffc-demo namespaces. But once it run it worked fine.
> 
> image

Did you check the `/healthy` endpoint as well as `/healthz`?
I'm currently having difficulty deploying anything to my local cluster as Helm just freezes after the resources have been created. Will take another look tomorrow.

**Comment by johnwatson484** [comment]
> > It works fine for me? I had a bit of an issue getting the install script to run, not sure what I did to fix it other than clearing out any existing ffc-demo namespaces. But once it run it worked fine.
> 
> Did you check the `/healthy` endpoint as well as `/healthz`?
> I'm currently having difficulty deploying anything to my local cluster as Helm just freezes after the resources have been created. Will take another look tomorrow.

I thought I checked both and just sent wrong screenshot, but on rechecking, I'm now getting a 500 error too. 

Issue is the connection to artemis is being refused in k8s.  I've tried to spot the issue with no luck all seems configured correct.  Also the issue exists in master branch so is not related to these changes.

Suggest we create a bug ticket to fix rather than extend the scope of this ticket?

**Comment by djbingham** [comment]
> Issue is the connection to artemis is being refused in k8s. I've tried to spot the issue with no luck all seems configured correct. Also the issue exists in master branch so is not related to these changes.

Weird, I was not getting the issue in `master`. Maybe it's intermittent.

> Suggest we create a bug ticket to fix rather than extend the scope of this ticket?

:+1: Agreed.

**Pull request merged**
